services:
    psmoduler.admin.representatives.grids.definitions.factories.representatives:
        class: 'Psmoduler\Admin\Sections\Representatives\Grids\Definitions\Factories\RepresentativeGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

    psmoduler.admin.representatives.grids.queries.representative:
        class: 'Psmoduler\Admin\Sections\Representatives\Grids\Queries\RepresentativeQueryBuilder'
        parent: 'prestashop.core.grid.abstract_query_builder'
        public: true
        arguments:
            - '@prestashop.core.query.doctrine_search_criteria_applicator'
            - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

    psmoduler.admin.representatives.grids.data_provider.representatives:
        class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
        arguments:
            - '@psmoduler.admin.representatives.grids.queries.representative'
            - '@prestashop.core.hook.dispatcher'
            - '@prestashop.core.grid.query.doctrine_query_parser'
            - 'representative'

    psmoduler.admin.representatives.grids.factories.representatives:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@psmoduler.admin.representatives.grids.definitions.factories.representatives'
            - '@psmoduler.admin.representatives.grids.data_provider.representatives'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'
