services:
    psmoduler.admin.representatives.repositories.representative:
        class: Psmoduler\Admin\Sections\Representatives\Repositories\RepresentativeRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - Psmoduler\Entity\Admin\Sections\Representatives\PsmodulerRepresentative
