psmoduler_admin_representatives_index:
    path: /
    methods: [GET]
    defaults:
        _controller: 'Psmoduler\Admin\Sections\Representatives\Http\Controllers\RepresentativeController::index'
        _legacy_controller: 'PsmodulerAdminRepresentativesRepresentative'
        _legacy_link: 'PsmodulerAdminRepresentativesRepresentative'

psmoduler_admin_representatives_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: 'Psmoduler\Admin\Sections\Representatives\Http\Controllers\RepresentativeController::create'
        _legacy_controller: 'PsmodulerAdminRepresentativesRepresentative'
        _legacy_link: 'PsmodulerAdminRepresentativesRepresentative:add'

psmoduler_admin_representatives_edit:
    path: /{idRepresentative}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'Psmoduler\Admin\Sections\Representatives\Http\Controllers\RepresentativeController::edit'
        _legacy_controller: 'PsmodulerAdminRepresentativesRepresentative'
        _legacy_link: 'PsmodulerAdminRepresentativesRepresentative:update'
    requirements:
        quoteId: \d+

psmoduler_admin_representatives_delete:
    path: /{idRepresentative}/delete
    methods: [DELETE]
    defaults:
        _controller: 'Psmoduler\Admin\Sections\Representatives\Http\Controllers\RepresentativeController::delete'
        _legacy_controller: 'PsmodulerAdminRepresentativesRepresentative'
        _legacy_link: 'PsmodulerAdminRepresentativesRepresentative:delete'
    requirements:
        quoteId: \d+

psmoduler_admin_representatives_bulk_delete:
    path: /bulkDelete
    methods: [POST]
    defaults:
        _controller: 'Psmoduler\Admin\Sections\Representatives\Http\Controllers\RepresentativeController::deleteBulk'
        _legacy_controller: 'PsmodulerAdminRepresentativesRepresentative'
        _legacy_link: 'PsmodulerAdminRepresentativesRepresentative:submitBulkdelete'
