services:
    psmoduler.admin.representatives.toolbars.representative:
        class: 'Psmoduler\Admin\Sections\Representatives\Toolbars\RepresentativeToolbar'
        arguments:
            - '@translator'
            - '@router'
