services:

    psmoduler.admin.representatives.forms.representative:
        class: 'Psmoduler\Admin\Sections\Representatives\Forms\RepresentativeType'
        parent: 'form.type.translatable.aware'
        public: true
        arguments:
            - '@psmoduler.admin.representatives.repositories.representative'
            - '@request_stack'
            - '@=service("prestashop.adapter.multistore_feature").isUsed()'
        tags:
            - { name: form.type }

    psmoduler.admin.representatives.forms.identifiable_object.data_provider.representative_form_data_provider:
        class: 'Psmoduler\Admin\Sections\Representatives\Forms\RepresentativeFormDataProvider'
        arguments:
            - '@psmoduler.admin.representatives.repositories.representative'
            - '@psmoduler.admin.representatives.services.representative'

    psmoduler.admin.representatives.forms.identifiable_object.builder.representative_form_builder:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
        factory: 'prestashop.core.form.builder.form_builder_factory:create'
        arguments:
            - 'Psmoduler\Admin\Sections\Representatives\Forms\RepresentativeType'
            - '@psmoduler.admin.representatives.forms.identifiable_object.data_provider.representative_form_data_provider'

    psmoduler.admin.representatives.forms.identifiable_object.data_handler.representative_form_data_handler:
        class: 'Psmoduler\Admin\Sections\Representatives\Forms\RepresentativeFormDataHandler'
        arguments:
            - '@psmoduler.admin.representatives.repositories.representative'
            - '@doctrine.orm.default_entity_manager'

    psmoduler.admin.representatives.forms.identifiable_object.handler.representative_form_handler:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
        factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
        arguments:
            - '@psmoduler.admin.representatives.forms.identifiable_object.data_handler.representative_form_data_handler'
