services:
    psmoduler.admin.representatives.services.representative:
        class: Psmoduler\Admin\Sections\Representatives\Services\RepresentativeService
        arguments:
            - '@prestashop.core.admin.lang.repository'
            - '@doctrine.orm.default_entity_manager'
