services:
    psmoduler.admin.representatives.services.representative:
        class: Psmoduler\Admin\Sections\Representatives\Services\RepresentativeService
        arguments:
            - '@prestashop.core.admin.lang.repository'
            - '@psmoduler.admin.representatives.repositories.representative'
