# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
psmoduler_admin_representative_index:
    path: /psmoduler/representatives
    methods: [GET]
    defaults:
        _controller: 'Psmoduler\Controller\Admin\RepresentativeController::indexAction'
        _legacy_controller: 'PsmodulerAdminRepresentatives'
        _legacy_link: 'PsmodulerAdminRepresentatives'
